sonar.projectKey=HR-Fahim_8.2CDevSecOps
sonar.organization=hr-fahim
sonar.host.url=https://sonarcloud.io

sonar.sources=app.js,utils.js,routes,service,entity,public

sonar.tests=tests

# Exclusions for files and directories that should not be analyzed to reduce noise and focus on relevant code. 
sonar.exclusions=node_modules/**,tests/**,exploits/**,snyk-report.json,package-lock.json,public/js/bundle.js

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8