sonar.projectKey=HR-Fahim_8.2CDevSecOps
sonar.organization=hr-fahim
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.tests=tests

sonar.exclusions=node_modules/**,tests/**,public/js/bundle.js

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8