sonar.projectKey=HR-Fahim_8.2CDevSecOps

sonar.sources=.

sonar.tests=tests

sonar.test.inclusions=tests/**/*.test.js,tests/**/*.spec.js

sonar.exclusions=node_modules/**,coverage/**,snyk-report.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8

# Making the scanner wait for the Quality Gate and failing the analysis when the Quality Gate is not passed.
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=600