name: "snyk code manual test"
on: [push, pull_request]

jobs:
  build:
    name: sarif testing action
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@8dca8a82e2fa1a2c8908956f711300f9c4a4f4f6
        with:
          sarif_file: sarif.json
          # sarif_file: example111.json
